version: '2.1'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./BlogSamples.Containers.sln && dotnet publish ./BlogSamples.Containers.sln -c Release -o ./obj/Docker/publish"
